/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId';
import { Route as CasesIndexRouteImport } from './routes/cases/index';
import { Route as IndexRouteImport } from './routes/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any);
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/cases/$caseId': typeof CasesCaseIdRoute;
  '/cases/': typeof CasesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/cases/$caseId': typeof CasesCaseIdRoute;
  '/cases': typeof CasesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/cases/$caseId': typeof CasesCaseIdRoute;
  '/cases/': typeof CasesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/cases/$caseId' | '/cases/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/cases/$caseId' | '/cases';
  id: '__root__' | '/' | '/cases/$caseId' | '/cases/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CasesCaseIdRoute: typeof CasesCaseIdRoute;
  CasesIndexRoute: typeof CasesIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/cases/': {
      id: '/cases/';
      path: '/cases';
      fullPath: '/cases/';
      preLoaderRoute: typeof CasesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/cases/$caseId': {
      id: '/cases/$caseId';
      path: '/cases/$caseId';
      fullPath: '/cases/$caseId';
      preLoaderRoute: typeof CasesCaseIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
